#!/bin/env bash
set -eax

python -m Pojazdy.populate-pojazdy
python -m Ubezpieczenia.populate-ubezpieczenia
python -m Osoby.populate-osoby
python -m Osoby_Pojazdy.populate-osoby-pojazdy
python -m Prawa_Jazdy.populate-prawa-jazdy
python -m Funkcjonariusze.populate-funkcjonariusze
python -m Zdarzenia.populate-zdarzenia
python -m Interwencje.populate-interwencje
# Role_Zdarzenia
python -m Uczestnicy_Zdarzenia.populate-uczestnicy-zdarzenia
python -m Wykroczenia.populate-wykroczenia
python -m Formy_Wymiaru_Kary.populate-formy-wymiaru-kary
python -m Aresztowania.populate-aresztowania
python -m Mandaty.populate-mandaty
